'use strict';
const concepts={
 foco:['Ponto focal','É a zona que chama primeiro a atenção. Um elemento diferente pode interromper a repetição e tornar-se protagonista.','Qual dos círculos viste primeiro?','Círculos azuis iguais com um círculo maior em verde.'],
 contraste:['Contraste','A diferença entre claro e escuro ajuda a destacar formas e texto. Na comparação, os tons aproximam-se e a leitura perde força.','Consegues ler a mensagem à distância nas duas versões?','Círculo e texto verdes sobre fundo escuro, ou tons semelhantes de cinzento na comparação.'],
 escala:['Escala','O tamanho é uma escolha de comunicação. Um círculo muito maior torna-se dominante, mesmo mantendo a cor dos outros.','O que acontece quando todos voltam a ter o mesmo tamanho?','Um círculo azul maior entre círculos pequenos, ou todos do mesmo tamanho na comparação.'],
 composicao:['Composição','Organiza a relação entre imagem, texto e margens. Alinhamento e agrupamento ajudam a criar uma ordem de leitura.','Em que versão o percurso entre a imagem e o texto te parece mais claro?','Grupo de círculos no canto superior direito e texto alinhado em baixo; na comparação, grupo centrado e texto inclinado.'],
 cor:['Cor','A mesma composição pode sugerir sensações diferentes com cores quentes ou frias. Aqui a comparação é uma alternativa, não uma resposta errada.','Que sensação te transmite cada paleta? A tua resposta coincide com a de um colega?','Paleta de laranja e verde, ou alternativa em tons azuis na comparação.'],
 tipo:['Tipografia','A forma, o peso e o espaçamento das letras influenciam a leitura. Escolhe letras que combinem com a mensagem e sejam legíveis.','Que versão consegues ler mais depressa?','Texto grande e forte, ou letras menores, serifadas e mais espaçadas na comparação.'],
 espaco:['Espaço negativo','É o espaço livre à volta dos elementos. Ajuda a separar, destacar e criar pausas. Não precisas de preencher a folha toda.','O cartaz continua a respirar quando os elementos ocupam quase toda a área?','Círculos pequenos rodeados de espaço livre, ou círculos ampliados e margens reduzidas na comparação.']
};
const poster=document.querySelector('#lab-poster'), comparison=document.querySelector('#before');
let current='foco';
function renderConcept(){const c=concepts[current];document.querySelector('#concept-title').textContent=c[0];document.querySelector('#concept-desc').textContent=c[1];document.querySelector('#concept-question').textContent=c[2];poster.dataset.mode=current;poster.classList.toggle('before',comparison.checked);poster.setAttribute('aria-label',`Experiência sobre ${c[0]}. ${c[3]} Texto: Faz a diferença. A tua voz também conta. Versão ${comparison.checked?'de comparação':'principal'}.`);}
document.querySelectorAll('[data-concept]').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.concept;comparison.checked=false;document.querySelectorAll('[data-concept]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderConcept();}));comparison.addEventListener('change',renderConcept);
const ideas={telemovel:'Um ecrã pode transformar-se numa gaiola. Que outra imagem representa a falta de liberdade?',ambiente:'E se uma folha de árvore se transformasse num pulmão? Que relação queres mostrar entre natureza e vida?',bullying:'E se as palavras deixassem marcas visíveis? Como podes mostrar o impacto de uma mensagem sem desenhar uma agressão?',igualdade:'Uma linha de partida é realmente igual para todos? Como podes transformar essa ideia numa imagem?',consumo:'E se um saco de compras tivesse um peso impossível? O que transportamos quando compramos sem pensar?',musica:'E se os sons tivessem formas? Como podes traduzir um ritmo numa composição para um evento inventado?'};
document.querySelector('#theme').addEventListener('change',e=>{document.querySelector('#theme-idea').textContent=ideas[e.target.value];});
const checks=[...document.querySelectorAll('[data-check]')], key='ev-cartaz-checklist-v1';
let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{}
checks.forEach(c=>{c.checked=saved[c.dataset.check]===true;c.addEventListener('change',updateProgress);});
function updateProgress(){const count=checks.filter(c=>c.checked).length;document.querySelector('#progress').value=count;document.querySelector('#progress-text').textContent=count===7?'7 de 7 verificações concluídas. Está tudo revisto!':`${count} de 7 verificações concluídas.`;try{localStorage.setItem(key,JSON.stringify(Object.fromEntries(checks.map(c=>[c.dataset.check,c.checked]))));}catch{document.querySelector('.checklist ~ .caption').textContent='A lista funciona nesta visita, mas este navegador não permitiu guardar as marcações. Não envia respostas à professora.';}}
updateProgress();document.querySelector('#reset').addEventListener('click',()=>{checks.forEach(c=>c.checked=false);updateProgress();});document.querySelector('#print').addEventListener('click',()=>window.print());
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');
const campaignCards=[...document.querySelectorAll('[data-campaign]')];let ticking=false;
function moveArt(){campaignCards.forEach((card,i)=>card.style.setProperty('--drift',reduce.matches?'0px':`${Math.min(window.scrollY,850)*[.035,-.045,.06][i]}px`));ticking=false;}
window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(moveArt);ticking=true;}},{passive:true});reduce.addEventListener('change',moveArt);
const campaigns={
 trees:{image:'assets/campanha-arvores.jpg',alt:'Uma folha em azul e preto ocupa a parte superior do cartaz Spare Our Trees.',title:'Spare Our Trees',meta:'STANLEY THOMAS CLOUGH · 1938',context:'Cartaz de conservação das árvores, produzido pelo Federal Art Project / WPA, no Ohio. Fonte: Library of Congress.',message:'«Preservem as nossas árvores.» Uma única folha representa uma causa maior: a proteção das árvores.',analysis:'A folha domina pela escala. As cores reduzidas e o fundo claro tornam a silhueta legível. O texto, isolado na parte inferior, fecha a leitura sem disputar espaço com a imagem.',question:'Se em vez desta folha houvesse vinte árvores pequenas, o impacto seria o mesmo?',source:'https://www.loc.gov/item/98517129/'},
 work:{image:'assets/campanha-we-can-do-it.jpg',alt:'Trabalhadora de camisa azul e lenço vermelho dobra o braço sob a frase We Can Do It!, num fundo amarelo.',title:'We Can Do It!',meta:'J. HOWARD MILLER · C. 1942–1943',context:'Criado para a Westinghouse durante a Segunda Guerra Mundial e usado inicialmente dentro das suas fábricas. Tornou-se amplamente conhecido décadas depois. Fonte: National Archives.',message:'«Somos capazes!» O cartaz procura transmitir força, determinação e confiança coletiva no contexto de trabalho da época.',analysis:'O fundo amarelo contrasta com a camisa azul. O rosto e o braço formam o centro de atenção, enquanto a frase curta no topo funciona como uma voz que fala diretamente ao observador.',question:'Que sensação mudaria se a figura estivesse de costas ou olhasse para o chão?',source:'https://www.archives.gov/research/still-pictures/highlights/we-can-do-it'},
 water:{image:'assets/campanha-agua.jpg',alt:'Cartaz Don’t be a drip! com apelos a reparar fugas e a poupar água.',title:'Don’t be a drip!',meta:'CHARLOTTE ANGUS · 1941–1943',context:'Produzido pela Penna Art WPA para o Philadelphia Council of Defense, durante a Segunda Guerra Mundial. Fonte: Library of Congress.',message:'Evitar o desperdício de água: reparar fugas e poupar um recurso. O apelo associa um gesto do dia a dia a uma responsabilidade coletiva.',analysis:'A imagem da torneira concretiza o problema. As frases curtas no imperativo transformam a observação numa ação: parar as fugas e poupar água.',question:'Como farias um cartaz sobre o mesmo tema com uma metáfora visual e apenas três palavras?',source:'https://www.loc.gov/item/98518712/'}
};
const campaignDialog=document.querySelector('#campaign-dialog');let openedBy=null;
campaignCards.forEach(card=>card.addEventListener('click',()=>{const c=campaigns[card.dataset.campaign];openedBy=card;document.querySelector('#campaign-image').src=c.image;document.querySelector('#campaign-image').alt=c.alt;['title','meta','context','message','analysis','question'].forEach(k=>document.querySelector('#campaign-'+k).textContent=c[k]);document.querySelector('#campaign-source').href=c.source;campaignDialog.showModal();document.body.style.overflow='hidden';}));
document.querySelector('.close-dialog').addEventListener('click',()=>campaignDialog.close());
campaignDialog.addEventListener('click',e=>{if(e.target===campaignDialog){const r=campaignDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)campaignDialog.close();}});
campaignDialog.addEventListener('close',()=>{document.body.style.overflow='';openedBy?.focus({preventScroll:true});});
