'use strict';
const concepts={
 foco:['Ponto focal','É a zona que chama primeiro a atenção. Um elemento diferente pode interromper a repetição e tornar-se protagonista.','Qual dos círculos viste primeiro?','Círculos azuis iguais com um círculo maior em verde.'],
 contraste:['Contraste','A diferença entre claro e escuro ajuda a destacar formas e texto. Na comparação, os tons aproximam-se e a leitura perde força.','Consegues ler a mensagem à distância nas duas versões?','Círculo e texto verdes sobre fundo escuro, ou tons semelhantes de cinzento na comparação.'],
 escala:['Escala','O tamanho é uma escolha de comunicação. Um círculo muito maior torna-se dominante, mesmo mantendo a cor dos outros.','O que acontece quando todos voltam a ter o mesmo tamanho?','Um círculo azul maior entre círculos pequenos, ou todos do mesmo tamanho na comparação.'],
 composicao:['Composição','Organiza a relação entre imagem, texto e margens. Alinhamento e agrupamento ajudam a criar uma ordem de leitura.','Em que versão o percurso entre a imagem e o texto te parece mais claro?','Grupo de círculos no canto superior direito e texto alinhado em baixo; na comparação, grupo centrado e texto inclinado.'],
 cor:['Cor','A mesma composição pode sugerir sensações diferentes com cores quentes ou frias. Aqui a comparação é uma alternativa, não uma resposta errada.','Que sensação te transmite cada paleta? A tua resposta coincide com a de um colega?','Paleta de laranja e verde, ou alternativa em tons azuis na comparação.'],
 tipo:['Tipografia','A forma, o peso e o espaçamento das letras influenciam a leitura. Escolhe letras que combinem com a mensagem e sejam legíveis.','Que versão consegues ler mais depressa?','Texto grande e forte, ou letras menores, serifadas e mais espaçadas na comparação.'],
 espaco:['Espaço negativo','É o espaço livre à volta dos elementos. Ajuda a separar, destacar e criar pausas. Não precisas de preencher a folha toda.','O cartaz continua a respirar quando os elementos ocupam quase toda a área?','Círculos pequenos rodeados de espaço livre, ou círculos ampliados e margens reduzidas na comparação.']
};
const poster=document.querySelector('#lab-poster'), comparison=document.querySelector('#before');
let current='foco';
function renderConcept(){const c=concepts[current];document.querySelector('#concept-title').textContent=c[0];document.querySelector('#concept-desc').textContent=c[1];document.querySelector('#concept-question').textContent=c[2];poster.dataset.mode=current;poster.classList.toggle('before',comparison.checked);poster.setAttribute('aria-label',`Experiência sobre ${c[0]}. ${c[3]} Texto: Faz a diferença. A tua voz também conta. Versão ${comparison.checked?'de comparação':'principal'}.`);}
document.querySelectorAll('[data-concept]').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.concept;comparison.checked=false;document.querySelectorAll('[data-concept]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderConcept();}));comparison.addEventListener('change',renderConcept);
const ideas={telemovel:'Um ecrã pode transformar-se numa gaiola. Que outra imagem representa a falta de liberdade?',ambiente:'E se uma folha de árvore se transformasse num pulmão? Que relação queres mostrar entre natureza e vida?',bullying:'E se as palavras deixassem marcas visíveis? Como podes mostrar o impacto de uma mensagem sem desenhar uma agressão?',igualdade:'Uma linha de partida é realmente igual para todos? Como podes transformar essa ideia numa imagem?',consumo:'E se um saco de compras tivesse um peso impossível? O que transportamos quando compramos sem pensar?',musica:'E se os sons tivessem formas? Como podes traduzir um ritmo numa composição para um evento inventado?'};
document.querySelector('#theme').addEventListener('change',e=>{document.querySelector('#theme-idea').textContent=ideas[e.target.value];});
const checks=[...document.querySelectorAll('[data-check]')], key='ev-cartaz-checklist-v1';
let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{}
checks.forEach(c=>{c.checked=saved[c.dataset.check]===true;c.addEventListener('change',updateProgress);});
function updateProgress(){const count=checks.filter(c=>c.checked).length;document.querySelector('#progress').value=count;document.querySelector('#progress-text').textContent=count===7?'7 de 7 verificações concluídas. Está tudo revisto!':`${count} de 7 verificações concluídas.`;try{localStorage.setItem(key,JSON.stringify(Object.fromEntries(checks.map(c=>[c.dataset.check,c.checked]))));}catch{document.querySelector('.checklist ~ .caption').textContent='A lista funciona nesta visita, mas este navegador não permitiu guardar as marcações. Não envia respostas à professora.';}}
updateProgress();document.querySelector('#reset').addEventListener('click',()=>{checks.forEach(c=>c.checked=false);updateProgress();});document.querySelector('#print').addEventListener('click',()=>window.print());
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');const art=document.querySelector('.hero-art');let ticking=false;
function moveArt(){art.style.transform=reduce.matches?'none':`translateY(${Math.min(window.scrollY,750)*.16}px)`;ticking=false;}
window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(moveArt);ticking=true;}},{passive:true});reduce.addEventListener('change',moveArt);
